### ISSUE TITLE
Upgrade to jruby 1.6.2

### ISSUE THREAD

**Issue by jeppenejsum** [RobertFischer/gradle-plugins#15]
Hi 

Could you upgrade the jruby dep to 1.6.2

After reviving #14, I know get errors resembling http://jira.codehaus.org/browse/JRUBY-5581 which should be fixed in 1.6.2

/Jeppe

**Comment by RobertFischer** [comment]
Done: 0.8.2 release, which is already at repo.smokejumperit.com

~~ Robert.

On Thu, May 26, 2011 at 3:45 AM, jeppenejsum
reply@reply.github.com
wrote:

**Comment by fleetzone** [comment]
I can confirm that upgrading to 1.6.2 solved my problem and I'm able to run my migrations from gradle again :-)

I had a few other issues though, not sure if these are in Ruby/JRuby/Plugin

1) I cannot build gradle-plugins locally, fails with an NPE in UploadArchices when trying to load property. Might make this lazy upon execution, not initialization

2) I have this task:

def runDBTask(task) {
  project.useGem('rake')
  project.useGem('activerecord')
  project.useGem('activerecord-jdbcpostgresql-adapter')
  def rakeBin = project.gemScript('rake')
  project.runJRuby("-C db $rakeBin --trace $task DATABASE=fleetzone")
}

First time I run:

rm -rf /Users/jeppe/.gem/ && ./gradlew dbUpdateSchema

it fails with:
14:58:07.841 [INFO] [com.smokejumperit.gradle.RunJRubyPlugin] Running JRuby: -S gem install --no-rdoc --no-ri --install-dir '/Users/jeppe/.gem' rake
Fetching: rake-0.9.0.gem (100%)t] Fetching: rake-0.9.0.gem
14:58:18.961 [DEBUG] [com.smokejumperit.gradle.RunJRubyPlugin] Done running JRuby: -S gem install --no-rdoc --no-ri --install-dir '/Users/jeppe/.gem' rake
14:58:18.962 [DEBUG] [org.gradle.api.internal.tasks.SkipTaskExecuter] Finished executing task ':dbUpdateSchema'
14:58:18.975 [ERROR] [org.gradle.BuildExceptionReporter] 
14:58:18.978 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
14:58:18.979 [ERROR] [org.gradle.BuildExceptionReporter] 
14:58:18.979 [ERROR] [org.gradle.BuildExceptionReporter] \* Where:
14:58:18.980 [ERROR] [org.gradle.BuildExceptionReporter] Build file '/Users/jeppe/Documents/workspaces/fleetzone/fleetweb/build.gradle' line: 254
14:58:18.980 [ERROR] [org.gradle.BuildExceptionReporter] 
14:58:18.981 [ERROR] [org.gradle.BuildExceptionReporter] \* What went wrong:
14:58:18.981 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':dbUpdateSchema'.
14:58:18.985 [ERROR] [org.gradle.BuildExceptionReporter] Cause: java.lang.AbstractMethodError: org.jruby.ext.JRubyPOSIXHandler.error(Lorg/jruby/ext/posix/POSIX$ERRORS;Ljava/lang/String;)V
14:58:18.985 [ERROR] [org.gradle.BuildExceptionReporter] 
14:58:18.986 [ERROR] [org.gradle.BuildExceptionReporter] \* Exception is:
14:58:18.991 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.LocationAwareTaskExecutionException: Build file '/Users/jeppe/Documents/workspaces/fleetzone/fleetweb/build.gradle' line: 254
14:58:18.992 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':dbUpdateSchema'.

When I run ./gradlew dbUpdateSchema again it installs the remaining gems, but it fails with:

15:01:19.200 [INFO] [com.smokejumperit.gradle.RunJRubyPlugin] Running JRuby: -C db /Users/jeppe/.gem/gems/rake-0.9.0/bin/rake --trace db:migrate DATABASE=fleetzone
15:01:23.492 [QUIET] [system.out](in /Users/jeppe/Documents/workspaces/fleetzone/fleetweb/db)
15:01:23.508 [QUIET] [system.out] *\* Invoke db:migrate (first_time)
15:01:23.510 [QUIET] [system.out] *\* Invoke db:ar_init (first_time)
15:01:23.510 [QUIET] [system.out] *\* Execute db:ar_init
15:01:23.524 [ERROR] [system.err] rake aborted!
15:01:23.542 [ERROR] [system.err] no such file to load -- active_record
15:01:23.546 [ERROR] [system.err] org/jruby/RubyKernel.java:1038:in `require'
15:01:23.546 [ERROR] [system.err] file:/Users/jeppe/.gradle/cache/org.jruby/jruby-complete/jars/jruby-complete-1.6.2.jar!/META-INF/jruby.home/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:29:in`require'

I noticed that by default useGem installs into ~/.gem, not the default jruby location.

If I instead do export GEM_HOME=/Users/jeppe/.gem/jruby/1.8 first, I don't get the last error (but still have to run it twice)

so perhaps the default gemHome should be changed?

/Jeppe

**Comment by jeppenejsum** [comment]
Sorry used wrong account for last reply :-)

Awesome with the update, the above issues remain though, not sure what the root cause is...let me know if you need more info

/Jeppe

**Comment by RobertFischer** [comment]
#1) Don't run uploadArchives.  It's currently hard-coded to upload to
repo.smokejumperit.com, and you don't have access to that.
If you _are_ going to be running uploadArchives, you need to set the
following System properties:
sjit.repo.user
sjit.repo.keyFile
sjit.repo.passphrase
And then update the URL on 53 to point to where you want to deploy.
Also, you'll want to run gradle as `gradle --no-daemon` if it seems to
be missing System properties.

#2a) Looks like that error is inside JRuby, which is stopping the
installation. If there's something I can do to help, let me know.

#2b) I'm happy to change gemHome to whatever you think it should be.
Just let me know exactly where it should point. I'm a Java guy who
mucks about with JRuby now and again, so I'm happy to take advice on
JRuby configuration stuff. There's been some recurring problems with
gems not being fully recognized, but I'm kinda at a loss to debug
that.

BTW) This plugin is going to become its own plugin: I'm looking for
some funding to take time off and flesh it out—let me know if you have
a lead. The goals are to integrate JRuby into the normal Gradle
compile process, to use the user's JRuby (if available) and only
failing that to fall back to installing our own. I'd also like to make
the JRuby configurable but with a sane default and a signal to use the
latest version.

~~ Robert.

On Thu, May 26, 2011 at 9:16 AM, fleetzone
reply@reply.github.com
wrote:

**Comment by jeppenejsum** [comment]
Re 1) I only ran "gradle jar", but the code in uploadArchives runs during the configuration phase

Re 2a+b) I'm just a Scala guy that chose ruby to migrate my databases so don't really have a clue :-) But it seems to work when I set it to the default (homedir) location used by JRuby. This is the output of gem env with JRuby 1.6.2:

~/Downloads/jruby-1.6.2/bin/jruby -S gem env
 GEM PATHS:
     - /Users/jeppe/Downloads/jruby-1.6.2/lib/ruby/gems/1.8
     - /Users/jeppe/.gem/jruby/1.8

**Comment by RobertFischer** [comment]
1) Fixed in c816a58.

2) So what should I use for the gemHome variable?

~~ Robert.

On Thu, May 26, 2011 at 9:48 AM, jeppenejsum
reply@reply.github.com
wrote:

**Comment by jeppenejsum** [comment]
2) I think   ~/.gem/jruby/1.8

At least that works for me :-) Not sure if jruby has some config setting that can be queried.

**Comment by RobertFischer** [comment]
Pushed the change. Not going to do a point release for that alone.

In the new version of this plugin, we'll be using the system JRuby, so
we won't have to muck about with this. If there isn't a system JRuby,
it doesn't matter what gemHome is as long as it is consistent. So this
current mess is really a problem of the hybrid system.

~~ Robert.

On Thu, May 26, 2011 at 10:28 AM, jeppenejsum
reply@reply.github.com
wrote:

**Comment by jeppenejsum** [comment]
Just as an FYI, I don't think this has anything to do with system vs no-system JRuby.

I tried this on plain Windows 7 machine (with no JRuby installed) and had the same issue, solved by setting GEM_HOME as above'

**Comment by RobertFischer** [comment]
My point is just that if you were to have JRuby installed on the
system and the plugin could use that installation, I wouldn't have to
think about pathing issues.

~~ Robert.

On Fri, May 27, 2011 at 10:28 AM, jeppenejsum
reply@reply.github.com
wrote:
